import { createSlice, nanoid } from "@reduxjs/toolkit";
const initialState = {
  chosenUsername: null,
  subscriptions: null,
  paymentMethods: null
};


export const onboardingSlice = createSlice({
  name: "onboarding",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setChosenUsername: (state, action) => {
      state.chosenUsername = action.payload
    },
    setUserPaymentInfo: (state, action) => {
      console.log({payload: action.payload})
      const {subscriptions, paymentMethods} = action.payload;
      state.subscriptions = subscriptions.data
      state.paymentMethods = paymentMethods.data
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: () => {},
});

export const {
  setChosenUsername,
  setUserPaymentInfo
} = onboardingSlice.actions;

export default onboardingSlice.reducer;
